.gitignore, .travis.yml, composer.json, src/BigBlueButton.php, src/Core/ApiMethod.php, src/Parameters/UpdateRecordingsParameters.php, src/Responses/UpdateRecordingsResponse.php, tests/BigBlueButtonTest.php, tests/Parameters/UpdateRecordingsParametersTest.php, tests/Responses/DeleteRecordingsResponseTest.php, tests/Responses/JoinMeetingResponseTest.php, tests/Responses/UpdateRecordingsResponseTest.php, tests/TestCase.php, tests/fixtures/update_recordings.xml
Implementation of updateRecordings for updating the metaParameters in a recording.
http://docs.bigbluebutton.org/dev/api.html#updaterecordings
This PR also includes a fix for passing travis-ci build with PHP 5.4 and standarized methods for deleteRecordings
=> Implemented updateRecordings

README.md
The badges looks like this now
=> Adde more badges for php versions and downloads

src/BigBlueButton.php
I've changed the vars $securitySalt, $bbbServerBaseUrl, $urlBuilder from private to protected to allow extend the class and change the construct
=> Changes privates variables to protected allowing extend the class

src/Responses/BaseResponse.php, tests/BigBlueButtonTest.php
=> Simplify response succes and failure return code

src/Parameters/CreateMeetingParameters.php, tests/Parameters/CreateMeetingParametersTest.php, tests/TestCase.php
- Added bbb-recording-ready-url
- callback URL needs to be URLEncoded
=> Added bbb-recording-ready-url

src/Parameters/CreateMeetingParameters.php, tests/Parameters/CreateMeetingParametersTest.php, tests/TestCase.php
Added `allowModsToUnmuteUsers` api
=> allowModsToUnmuteUsers

tests/TestCase.php
I fixed some tests, changes are:
`
->setLockSettingsLockOnJoinConfigurable($params['lockSettingsLockOnJoinConfigurable'])
`
instead of 
`
->setLockSettingsLockOnJoinConfigurable($params['lockSettingsLockOnJoin'])
`
and added
`
->addMeta('bbb-recording-ready-url', $params['meta_bbb-recording-ready-url']);
`
=> Fix some tests

src/Core/Attendee.php, src/Core/Meeting.php, tests/Responses/GetMeetingInfoResponseTest.php, tests/fixtures/get_meeting_info.xml
Improving the usage of MESSAGE-class by adding two functions returning the MODERATORS and VIEWERS of a meeting.
=> Functions to get subset of attendees

src/Parameters/HooksCreateParameters.php
on hooks create getRaw parameter set as boolean as per [documentation](https://docs.bigbluebutton.org/dev/webhooks.html#hookscreate)
=> On Create Hooks getRaw parameter set as boolean before return as string

src/BigBlueButton.php
Customize XML Response Timeout, in my case I like to adjust it to 2ms instead of your default 10ms
=> make XML Response timeout to be configurable

src/Core/Attendee.php
=> Fix "Node no longer exists" in Attendee

src/BigBlueButton.php
Public accessor for buildUrl for custom URL calls which is not supported by bbb-api
=> Public accessor for buildUrl

src/BigBlueButton.php
This is needed for setting proxy parameters, for example.
=> pass array with curl options

src/BigBlueButton.php, src/Core/Format.php, src/Core/Image.php, src/Core/Record.php, tests/Responses/GetRecordingsResponseTest.php, tests/fixtures/get_recordings.xml
Implementation for https://github.com/bigbluebutton/bigbluebutton-api-php/issues/178 and https://github.com/bigbluebutton/bigbluebutton-api-php/issues/147
=> Handle multiple recording formats

src/Parameters/CreateMeetingParameters.php, tests/Parameters/CreateMeetingParametersTest.php, tests/TestCase.php
This PR contains the three new api features which comes with BBB 2.6:
- notifyRecordingIsOn
- uploadExternalUrl
- uploadExternalDescription
=> New features BBB 2.6

src/Parameters/CreateMeetingParameters.php, src/Parameters/JoinMeetingParameters.php, tests/Parameters/GetMeetingInfoParametersTest.php, tests/Parameters/JoinMeetingParametersTest.php
With this PR i add missing features to the JoinMeeting Parameters and also one parameter in CreateMeeting Method. Also i write the tests for this PR and fix exist tests.
New JoinMeeting Parameters are:
- configToken
- guest
- defaultLayout
With PR fixes #110 and  fixes #184
=> add missing features

src/Core/Meeting.php, src/Parameters/CreateMeetingParameters.php, src/Parameters/JoinMeetingParameters.php
Improvements on MEETING:
- transform annotations to php7.4 (remove redundant annotations)
- some code improvements
- adding help-text from BBB-docs
=> Transform code to php74 and add text from bbb-docs

src/BigBlueButton.php
Solves a wrong check in the BBB-constructor
=> Bugfix check in BBB-constructor

.env, src/BigBlueButton.php, src/Util/UrlBuilder.php, tests/BigBlueButtonTest.php, tests/Util/UrlBuilderTest.php
This PR will enable to change dynamically the BaseURL and Secret.
This PR solves #165.
=> Enable the use of dynamic API URL

README.md, composer.json, src/Enum/DocumentOption.php, src/Parameters/Config/DocumentOptions.php, src/Parameters/DocumentableTrait.php, tests/Parameters/Config/DocumentOptionsTest.php, tests/Parameters/InsertDocumentParametersTest.php, tests/fixtures/insert_document_presentations_with_options.xml
1) This PR introduce php8.1
2) This PR is improving the (current) DocumentOptions
- use of native ENUM-Type
- better naming
- more robust
- tests added
=> Improve DocumentOptions
